version: "3"
services:
  rabbitmq:
    image: rabbitmq:3.8-management
    ports:
      - "5672:5672" # RabbitMQ
      - "15672:15672" # UI Admin
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  review-app:
    build: ./Review-App
    ports:
      - "5000:5000"
    command: npx nodemon review.js
    depends_on:
      - rabbitmq
