version: "3"
services:
  rabbitmq:
    image: rabbitmq:3.8-management
    ports:
      - "5672:5672" # RabbitMQ
      - "15672:15672" # UI Admin
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

  review-app:
    build: ./Review-App
    ports:
      - "5000:5000"
    command: npm start
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq:rabbitmq
  
  aktivitas-app:
    build: ./AktivitasUser-App
    ports:
      - "5004:5004"
    command: npm start
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq:rabbitmq

  cabang-app:
    build: ./Cabang-App
    ports:
      - "5002:5002"
    command: npm start
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq:rabbitmq